import pygame, SoundPlayer
WIDTH = 16
HEIGHT = 12
GRAVITY = 0.2
DEBUG = False
TILESIZE = 16
SCREENMULTIPLIER = 2
CANVAS = pygame.display.set_mode((WIDTH*TILESIZE*SCREENMULTIPLIER,
	HEIGHT*TILESIZE*SCREENMULTIPLIER))
FRAMECOUNT = 0

SOUNDPLAYER = SoundPlayer.SoundPlayer()
